services:
  mssb:
    image: 'baozaodetudou/mssb'
    container_name: mssb
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
    network_mode: "host"
    volumes:
      - './mssb:/mssb'
    restart: unless-stopped