log:
  level: error # 设置日志级别为error
  file: "./mosdns.log" # 日志文件路径
  production: false # 非生产环境配置

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 10240 # 缓存大小
      lazy_cache_ttl: 86400 # 缓存过期时间

  # 转发至国内DNS，并发查询
  - tag: forward_local
    type: forward
    args:
      concurrent: 4 # 并发查询数量
      upstreams:
        - addr: udp://221.130.33.60
        - addr: udp://221.179.155.161
        - addr: udp://119.29.29.29
        - addr: udp://223.5.5.5

#   # 转发至国外DNS，拿真实ip
#   - tag: forward_real
#     type: forward
#     args:
#       concurrent: 1 # 并发查询数量
#       upstreams:
#         #- addr: 192.168.20.5:6666  # 本地DNS服务器地址ipv4
#         #- addr: tcp://192.168.20.5:6666  # TCP协议的本地DNS服务器地址ipv4
#         - addr: tcp://8.8.8.8
#           socks5: "192.168.20.2:6153"

  # 转发至sb，拿fake ip
  - tag: forward_fake
    type: forward
    args:
      concurrent: 2 # 并发查询数量
      upstreams:
        - addr: tcp://127.0.0.1:6666
        - addr: udp://127.0.0.1:6666

  # 自定义hosts
  - tag: hosts
    type: hosts
    args:
      files:
        - "./hosts.txt"

  # china ip和自己的vps ip
  - tag: local_ip
    type: ip_set
    args:
      files:
        - ./china_ip_list.txt
        - ./myvpsip.txt

  # fallback的primary服务器,只接受国内ip，丢弃非国内ip
  - tag: local_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: "resp_ip $local_ip" # 检查是否是国内IP
        exec: accept # 如果是国内IP，则接受
      - exec: drop_resp # 丢弃非国内ip

  # fake_fallback的secondary服务器,直接接受结果
  - tag: fake_sequence
    type: sequence
    args:
      - exec: $forward_fake
      - exec: accept # fakeip全部接受

#   # real_fallback的secondary服务器,
#   - tag: real_sequence
#     type: sequence
#     args:
#       - exec: $forward_real
#       - matches: "!resp_ip $local_ip"
#         exec: accept # 只接受国外ip

#   # fallback_real sequence
#   - tag: fallback_real
#     type: fallback
#     args:
#       primary: local_sequence
#       secondary: real_sequence
#       threshold: 500 # 超时时间，单位为毫秒
#       always_standby: true # 总是保持备用

  # fallback_fake sequence
  - tag: fallback_fake
    type: fallback
    args:
      primary: local_sequence
      secondary: fake_sequence
      threshold: 500 # 超时时间，单位为毫秒
      always_standby: true # 总是保持备用

  # 主运行序列
  - tag: main_sequence
    type: sequence
    args:
      # 执行hosts解析
      - exec: $hosts
      - matches: has_resp
        exec: accept # 如果hosts解析有响应，则接受并返回

      # 拒绝HTTPS类型查询
      - matches: qtype 65
        exec: reject 3

      # 拒绝在拒绝列表中的域名
      - matches: qname &./reject-list.txt &./my-reject-list.txt
        exec: reject

      # 优先使用IPv4解析
      - exec: prefer_ipv4

      # ddns域名走国内
      - matches: "qname ./mydns.txt"
        exec: $forward_local
      - matches: has_resp
        exec: accept # 如果有响应，则接受

      # proxy-device-list & client-ip 匹配内网需翻墙设备&被禁域名，走fakeip
      - matches:
          - qname &./proxy-list.txt &./my-proxy-list.txt
          - client_ip &./proxy-device-list.txt
        exec: $forward_fake
      - matches: has_resp
        exec: accept # 如果有响应，则接受

      # 查找缓存，命中则接受
      - exec: $cache 10240 # 查找 cache。
      - matches:
          - has_resp
        exec: accept

      # 特定列表中的域名使用国内DNS解析
      - matches: qname &./direct-list.txt &./apple-cn.txt
        exec: $forward_local
      - matches: has_resp
        exec: accept # 如果有响应，则接受

    #   # 转发国外dns，走real ip
    #   - matches: qname &./proxy-list.txt
    #     exec: $forward_real
    #   - matches: has_resp
    #     exec: accept # 如果有响应，则接受

      # 执行fallback_fake策略兜底
      - exec: $fallback_fake

  # 启动监听服务
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence # 主运行序列入口
      listen: :53 # 监听UDP端口53

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence # 主运行序列入口
      listen: :53 # 监听TCP端口53

api:
  http: "0.0.0.0:8080" # API服务监听地址和端口
